name: 🎯 MathKids Direct Build (No Gradlew)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: ☕ Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: 🔧 Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.5'
        
    - name: 🧹 Clean project
      run: gradle clean
      
    - name: 🏗️ Build APK
      run: gradle assembleDebug
      
    - name: 📂 List build outputs
      run: |
        echo "=== Build outputs ==="
        find . -name "*.apk" -type f || echo "No APK found"
        ls -la app/build/outputs/apk/debug/ || echo "No debug folder"
        
    - name: 📦 Upload APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: mathkids-apk-direct
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7
        
    - name: ✅ Success
      if: success()
      run: |
        echo "🎉 Build completed successfully!"
        echo "📱 APK ready for download!"
