name: 🎯 MathKids APK (Minimal Build)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v3
      
    - name: ☕ Setup Java 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: 📱 Setup Android
      run: |
        sudo apt-get update
        sudo apt-get install -y android-sdk
        
    - name: 🔧 Fix gradlew
      run: |
        chmod +x ./gradlew
        ls -la gradlew
        
    - name: 🧹 Clean
      run: |
        ./gradlew clean || echo "Clean failed, continuing..."
        
    - name: 🏗️ Build
      run: |
        ./gradlew assembleDebug --stacktrace --info || echo "Build failed, checking..."
        
    - name: 📂 Check outputs
      run: |
        find . -name "*.apk" -type f
        ls -la app/build/outputs/apk/debug/ || echo "No debug folder"
        
    - name: 📦 Upload if exists
      run: |
        if [ -f app/build/outputs/apk/debug/app-debug.apk ]; then
          echo "APK found, uploading..."
          mkdir -p artifacts
          cp app/build/outputs/apk/debug/app-debug.apk artifacts/
        else
          echo "No APK found"
        fi
        
    - name: 📤 Upload artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: build-outputs
        path: |
          artifacts/
          app/build/outputs/
          build/
        retention-days: 1
